server:  
  port: 5432
#  servlet:
#    context-path: /api-role
        
#服务注册
eureka:
  instance:
    instance-id: spring-cloud-bus
    appname: ${spring.application.name}
  client:
    service-url: 
      #EurekaServer服务注册中心地址
      defaultZone: http://zhoubc:zhoubc@localhost:8761/eureka/   

spring:
  application:
    name: spring-cloud-consumers
  rabbitmq:
    host: localhost
    port: 5672
    username: zhoubc
    password: zhoubc
    virtual-host: /
    connection-timeout: 15000
    cache:
      channel:        size: 25
    

  
