#zipkin服务链路追踪  client端配置：
spring:
  zipkin:
    base-url: http://localhost:9411 #zipkin中心地址  
    sender:           
        type: web     #发送的数据类型 kafaka、rabbitmq、web
  sleuth:
      sampler:
        probability: 1  #采样比例 0-1  1全部采集

