server:  
  port: 8100
#  servlet:
#    context-path: /api-role
        
#服务注册
eureka:
  instance:
    instance-id: spring-cloud-consumers
    appname: ${spring.application.name}
    metadata-map:
     cluster: consumers  #自定义元数据，key/value都可以随便写
  client:
    service-url: 
      #EurekaServer服务注册中心地址
      defaultZone: http://zhoubc:zhoubc@localhost:8761/eureka/   

spring:
  application:
    name: spring-cloud-consumers
  security:
    user:
      name: zhoubc
      password: zhoubc
   #加载其他配置文件
  profiles:
#  include: feign,actuator,admin,sleuth,rabbitmq
    include: feign,actuator,rabbitmq
#   include: feign,actuator,sleuth,rabbitmq
  
