#rabbitmq 消息队列
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: zhoubc
    password: zhoubc
    virtual-host: /
    connection-timeout: 15000
    cache:
      channel:
        size: 25

    