server:  
  port: 9411
#  servlet:
#    context-path: /api-role
        
#服务注册
eureka:
  instance:
    instance-id: spring-cloud-sleuth
    #appname: ${spring.application.name}
  client:
    service-url: 
      #EurekaServer服务注册中心地址
      defaultZone: http://zhoubc:zhoubc@localhost:8761/eureka/   

spring:
  application:
    name: spring-cloud-sleuth
  #关闭本工程的推送到zipkin服务的功能
  zipkin:
    enabled: false
    
# ===========zipkin数据持久化配置============
#spring:
#  datasource:
#    schema: classpath:/mysql.sql
#    url: jdbc:mysql://127.0.0.1:3306/test?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
#    username: root
#    password: root
#    initialize: true
#    continueOnError: true
#
#zipkin:
#  storage:
#    type: mysql  
# ===========zipkin数据持久化配置============



#不加这个配置，zipkin会报错
management:
  metrics:
    web:
      server:
         auto-time-requests: false

