server:
  port: 8761

#注册中心eureka
eureka:
  instance:
    #appname: ${spring.application.name} #应用名，首先获取spring.application.name的值，如果取值为空，则取默认unknown。
    hostname: localhost 
    #hostname: myhost1
  client:
    registerWithEureka: false #是否向注册中心注册服务，默认为true
    fetchRegistry: false #是否检索服务
    serviceUrl:
      defaultZone: http://zhoubc:zhoubc@${eureka.instance.hostname}:${server.port}/eureka/
#    defaultZone: http://zhoubc:zhoubc@myhost2:8762/eureka/    #,http://zhoubc:zhoubc@myhost2:8762/eureka/
spring:
  application:
    name: eureka-server   
   #注册中心eureka用户密码
  security:
    user:
      name: zhoubc
      password: zhoubc




